"""
whatsapp_sender.py
------------------
Outbound WhatsApp notification dispatcher using Twilio API.
Dispatches critical maritime emergency alerts (such as geofence border crossings
and severe cyclone warnings) directly to fishermen's mobile phones.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Dict

import config

logger = logging.getLogger("orca.whatsapp_sender")


def format_breach_alert_message(breach_data: Dict[str, Any]) -> str:
    """Format a high-urgency WhatsApp alert message for a maritime boundary breach."""
    boundary = breach_data.get("boundary_name", "International Maritime Boundary Line")
    sector = breach_data.get("sector", "Territorial Border Sector")
    coords = breach_data.get("coordinates", {})
    lat = coords.get("lat", 0.0)
    lon = coords.get("lon", 0.0)
    dist = breach_data.get("distance_km", 0.0)
    bearing = breach_data.get("bearing_to_safety", 270)
    cardinal = breach_data.get("bearing_cardinal", "W")
    cg_number = breach_data.get("coastguard_number", "1554")
    now_utc = datetime.now(timezone.utc).strftime("%d-%b-%Y %H:%M UTC")

    return (
        f"🚨 *CRITICAL MARITIME BORDER CROSSING ALERT* 🚨\n"
        f"━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        f"*Tarang Coastal Surveillance System*\n\n"
        f"⚠️ *WARNING: INTERNATIONAL BOUNDARY BREACH*\n"
        f"Your GPS position indicates you have *CROSSED* the *{boundary}* into foreign territorial waters!\n\n"
        f"📍 *Position*: `{lat:.4f}°N, {lon:.4f}°E`\n"
        f"🌊 *Sector*: {sector}\n"
        f"📏 *Penetration*: ~{dist:.1f} km beyond Indian border\n"
        f"⏰ *Time*: {now_utc}\n\n"
        f"🧭 *IMMEDIATE CORRECTIVE ACTION*:\n"
        f"1. Halt all fishing and net-trawling operations immediately.\n"
        f"2. Steer compass heading *{int(bearing)}° ({cardinal})* towards Indian waters.\n"
        f"3. Maintain vigilance against foreign naval / coast guard interception.\n\n"
        f"📞 *EMERGENCY DISTRESS CONTACTS*:\n"
        f"• Indian Coast Guard Toll-Free: *{cg_number}*\n"
        f"• VHF Distress Frequency: *Channel 16* (156.8 MHz)\n"
        f"━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        f"_This automated emergency advisory was generated by Tarang Safety Advisor._"
    )


def send_whatsapp_message(to_phone: str, message_body: str) -> Dict[str, Any]:
    """
    Send an outbound WhatsApp message via Twilio API.
    Normalizes phone format (e.g. "+91 92364 54423" -> "whatsapp:+919236454423").
    If Twilio credentials are not configured, operates in safe simulation mode.
    """
    import os
    import re
    from pathlib import Path
    from dotenv import dotenv_values

    raw_phone = str(to_phone or "").strip()
    if not raw_phone:
        return {"success": False, "error": "No phone number provided"}

    # Strip whatsapp: prefix if already present for cleaner digit extraction
    if raw_phone.lower().startswith("whatsapp:"):
        raw_phone = raw_phone[len("whatsapp:"):]

    # Strip all non-digit and non-plus characters (e.g. spaces, dashes, parentheses)
    clean_digits = re.sub(r"[^\d+]", "", raw_phone)
    if not clean_digits:
        return {"success": False, "error": "Invalid phone number"}

    if not clean_digits.startswith("+"):
        if len(clean_digits) == 10 and clean_digits.isdigit():
            clean_digits = f"+91{clean_digits}"
        else:
            clean_digits = f"+{clean_digits}"

    clean_phone = f"whatsapp:{clean_digits}"

    # Always read dynamically from .env on disk first, falling back to os.environ / config
    base_dir = Path(__file__).parent.parent
    env_dict = {**dotenv_values(base_dir.parent / ".env"), **dotenv_values(base_dir / ".env")}
    account_sid = (env_dict.get("TWILIO_ACCOUNT_SID") or os.getenv("TWILIO_ACCOUNT_SID") or getattr(config, "TWILIO_ACCOUNT_SID", "")).strip()
    auth_token = (env_dict.get("TWILIO_AUTH_TOKEN") or os.getenv("TWILIO_AUTH_TOKEN") or getattr(config, "TWILIO_AUTH_TOKEN", "")).strip()
    sender = (env_dict.get("TWILIO_WHATSAPP_NUMBER") or os.getenv("TWILIO_WHATSAPP_NUMBER") or getattr(config, "TWILIO_WHATSAPP_NUMBER", "") or "whatsapp:+14155238886").strip()
    if not sender.lower().startswith("whatsapp:"):
        sender = f"whatsapp:{sender}"

    # If no credentials configured, simulate delivery safely
    if not account_sid or not auth_token:
        logger.warning(
            "[WhatsAppSender] TWILIO_ACCOUNT_SID or TWILIO_AUTH_TOKEN not configured. "
            "Simulating WhatsApp dispatch to %s:\n%s",
            clean_phone,
            message_body[:200],
        )
        return {
            "success": True,
            "simulated": True,
            "to": clean_phone,
            "from": sender,
            "message_preview": message_body[:250],
            "note": "Simulated dispatch. Add TWILIO_ACCOUNT_SID & TWILIO_AUTH_TOKEN to .env for real SMS delivery.",
        }

    try:
        from twilio.rest import Client
        client = Client(account_sid, auth_token)
        msg = client.messages.create(
            from_=sender,
            to=clean_phone,
            body=message_body,
        )
        logger.info("[WhatsAppSender] Message dispatched successfully! SID=%s to %s", msg.sid, clean_phone)
        return {
            "success": True,
            "simulated": False,
            "sid": msg.sid,
            "to": clean_phone,
            "status": msg.status,
        }
    except Exception as exc:
        err_str = str(exc)
        if "63015" in err_str or "could not find" in err_str.lower():
            friendly_err = f"Number {clean_phone} is not connected to Twilio WhatsApp Sandbox (or 72-hour session expired). Send 'join basic-hearing' to +1 415 523 8886 from this WhatsApp phone."
        else:
            friendly_err = err_str
        logger.exception("[WhatsAppSender] Failed to send WhatsApp message via Twilio: %s", exc)
        return {
            "success": False,
            "simulated": False,
            "error": friendly_err,
            "to": clean_phone,
        }


def send_geofence_breach_alert(to_phone: str, breach_data: Dict[str, Any]) -> Dict[str, Any]:
    """Convenience function: formats breach data and dispatches WhatsApp alert."""
    text = format_breach_alert_message(breach_data)
    return send_whatsapp_message(to_phone, text)


_breach_alert_last_sent: dict[str, float] = {}


def send_geofence_breach_alert_throttled(
    to_phone: str,
    breach_data: Dict[str, Any],
    cooldown_s: int = 30,
    force: bool = False,
) -> Dict[str, Any]:
    """Dispatches a breach alert only if cooldown period has elapsed since last dispatch."""
    import time
    clean_key = str(to_phone or "").strip().lower()
    now = time.time()
    last = _breach_alert_last_sent.get(clean_key, 0.0)
    elapsed = now - last

    if not force and elapsed < cooldown_s:
        remaining = int(cooldown_s - elapsed)
        logger.info("[WhatsAppSender] Breach alert to %s throttled (cooldown remaining: %ds)", to_phone, remaining)
        return {
            "success": False,
            "rate_limited": True,
            "cooldown_seconds": cooldown_s,
            "next_allowed_in_seconds": remaining,
            "note": f"WhatsApp alert rate-limited. Next alert allowed in {remaining}s.",
        }

    res = send_geofence_breach_alert(to_phone, breach_data)
    if res.get("success"):
        _breach_alert_last_sent[clean_key] = now
    return res

